export const bookConstants = {
    GET_BOOKS_REQUEST: 'GET_BOOKS_REQUEST',
    GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
    GET_BOOKS_FAILURE: 'GET_BOOKS_FAILURE',

    ADD_BOOK_REQUEST: 'ADD_BOOK_REQUEST',
    ADD_BOOK_SUCCESS: 'ADD_BOOK_SUCCESS',
    ADD_BOOK_FAILURE: 'ADD_BOOK_FAILURE',

    DELETE_BOOK_REQUEST: 'DELETE_BOOK_REQUEST',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAILURE: 'DELETE_BOOK_FAILURE',

    EDIT_BOOK_REQUEST: 'EDIT_BOOK_REQUEST',
    EDIT_BOOK_SUCCESS: 'EDIT_BOOK_SUCCESS',
    EDIT_BOOK_FAILURE: 'EDIT_BOOK_FAILURE'
};